-- Bhaktniwas Module v4.0 — Phase 1: Data Model
-- Introduces dynamic Bhaktniwas blocks, admin-configurable settings, and the new
-- booking-day / per-person-pricing columns. Room-domain data is disposable dev data
-- (confirmed) so related tables are truncated rather than backfilled in place.

-- 1) Fix standing operational gap: room_booking_seq was only ever created by hand-run SQL.
CREATE SEQUENCE IF NOT EXISTS room_booking_seq START WITH 1 INCREMENT BY 1;

-- 2) Reset disposable room-domain data so new NOT NULL columns can be added cleanly.
TRUNCATE TABLE room_amenity, room_block, room_booking_audit, room_audit, room_booking, room
    RESTART IDENTITY CASCADE;

-- 3) Dynamic Bhaktniwas blocks (replaces the old free-text Room.blockName).
CREATE TABLE bhaktniwas_block (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(10)  NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    description  VARCHAR(255),
    sort_order   INTEGER,
    is_active    BOOLEAN      NOT NULL DEFAULT true,
    CONSTRAINT uk_bhaktniwas_block_code UNIQUE (code)
);

INSERT INTO bhaktniwas_block (code, display_name, sort_order, is_active) VALUES
    ('BN1', 'Bhaktniwas 1', 1, true),
    ('BN2', 'Bhaktniwas 2', 2, true),
    ('BN3', 'Bhaktniwas 3', 3, true);

-- 4) Admin-configurable settings (key/value — new keys need no schema change).
CREATE TABLE app_config (
    config_key   VARCHAR(100) PRIMARY KEY,
    config_value VARCHAR(255) NOT NULL,
    description  VARCHAR(255)
);

INSERT INTO app_config (config_key, config_value, description) VALUES
    ('dayStartHour', '6', 'Hour (0-23) at which a new booking day begins.'),
    ('idProofMandatory', 'false', 'Makes ID proof fields required in the booking form.'),
    ('maxAdvanceBookingDays', '0', '0 = today only. Increase to allow advance bookings.');

-- 5) RoomCategory — pricing type (FIXED vs PERSON_COUNT for BN3-style categories).
ALTER TABLE room_category
    ADD COLUMN pricing_type VARCHAR(20) NOT NULL DEFAULT 'FIXED';

-- 6) Room — dynamic block FK + extra-person pricing.
ALTER TABLE room DROP COLUMN IF EXISTS block_name;

ALTER TABLE room
    ADD COLUMN bhaktniwas_block_id BIGINT NOT NULL REFERENCES bhaktniwas_block(id),
    ADD COLUMN allow_extra_person BOOLEAN NOT NULL DEFAULT false,
    ADD COLUMN extra_person_cost NUMERIC(10,2) NOT NULL DEFAULT 0,
    ALTER COLUMN default_security_deposit SET DEFAULT 0;

-- 7) RoomBooking — day-cycle, slot count, and penalty-reason columns.
ALTER TABLE room_booking
    ADD COLUMN num_persons INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN booking_date DATE,
    ADD COLUMN slot_number INTEGER,
    ADD COLUMN penalty_reason TEXT;
