-- Replace all existing Bartan (kitchen utensil rental) inventory with the
-- current physical price-list board (2026). Safe to hard-delete: RentalItem
-- stores its own name/rate snapshot at issue time (itemNameSnapshot,
-- rateAtIssue), so historical rentals do not depend on these rows.
DELETE FROM inventory_item WHERE category = 'BARTAN';

INSERT INTO inventory_item (category, material_name_hi, unit, rate, total_stock, is_active, created_at, updated_at) VALUES
('BARTAN', 'गंज (बडा)',              'NOS', 50,  50, true, now(), now()),
('BARTAN', 'गंज (मिडियम)',           'NOS', 40,  50, true, now(), now()),
('BARTAN', 'गंज (छोटा)',             'NOS', 30,  50, true, now(), now()),
('BARTAN', 'झाकती',                  'NOS', 5,   50, true, now(), now()),
('BARTAN', 'सिगडी',                  'NOS', 100, 50, true, now(), now()),
('BARTAN', 'चेयर (खुर्ची)',          'NOS', 5,   50, true, now(), now()),
('BARTAN', 'कढ़ाई (बडी)',            'NOS', 50,  50, true, now(), now()),
('BARTAN', 'कढ़ाई (मिडियम)',         'NOS', 40,  50, true, now(), now()),
('BARTAN', 'कढ़ाई (छोटी)',           'NOS', 30,  50, true, now(), now()),
('BARTAN', 'बाल्टी (स्टील)',         'NOS', 10,  50, true, now(), now()),
('BARTAN', 'जग',                     'NOS', 5,   50, true, now(), now()),
('BARTAN', 'थाली',                   'NOS', 2,   50, true, now(), now()),
('BARTAN', 'कटोरी',                  'NOS', 1,   50, true, now(), now()),
('BARTAN', 'चम्मच',                  'NOS', 5,   50, true, now(), now()),
('BARTAN', 'डवला',                   'NOS', 5,   50, true, now(), now()),
('BARTAN', 'कोपर (बडा)',             'NOS', 30,  50, true, now(), now()),
('BARTAN', 'कोपर (मिडियम)',          'NOS', 20,  50, true, now(), now()),
('BARTAN', 'कोपर (छोटा)',            'NOS', 10,  50, true, now(), now()),
('BARTAN', 'चावल (पंजा)',            'NOS', 5,   50, true, now(), now()),
('BARTAN', 'कटोरा',                  'NOS', 10,  50, true, now(), now()),
('BARTAN', 'पाट-बेलन',               'NOS', 20,  50, true, now(), now()),
('BARTAN', 'मेटींग (बडी)',           'NOS', 60,  50, true, now(), now()),
('BARTAN', 'मेटींग (छोटी)',          'NOS', 30,  50, true, now(), now()),
('BARTAN', 'सराटा (बडा)',            'NOS', 15,  50, true, now(), now()),
('BARTAN', 'सराटा (मिडियम)',         'NOS', 10,  50, true, now(), now()),
('BARTAN', 'सराटा (छोटा)',           'NOS', 10,  50, true, now(), now()),
('BARTAN', 'खलबत्ता',                'NOS', 10,  50, true, now(), now()),
('BARTAN', 'पावसी',                  'NOS', 10,  50, true, now(), now()),
('BARTAN', 'वाढनी',                  'NOS', 10,  50, true, now(), now()),
('BARTAN', 'किसनी',                  'NOS', 5,   50, true, now(), now()),
('BARTAN', 'झारा (बडा)',             'NOS', 10,  50, true, now(), now()),
('BARTAN', 'झारा (मिडियम)',          'NOS', 10,  50, true, now(), now()),
-- #33 skipped: illegible on the source photo
('BARTAN', 'चिमटा',                  'NOS', 10,  50, true, now(), now()),
('BARTAN', 'नमक-पात्र',              'NOS', 10,  50, true, now(), now()),
('BARTAN', 'बफे टेबल',               'NOS', 30,  50, true, now(), now()),
('BARTAN', 'धामा',                   'NOS', 10,  50, true, now(), now()),
('BARTAN', 'तावा (बडा)',             'NOS', 30,  50, true, now(), now()),
('BARTAN', 'तावा (मिडियम)',          'NOS', 20,  50, true, now(), now()),
('BARTAN', 'तावा (छोटा)',            'NOS', 20,  50, true, now(), now()),
('BARTAN', 'कोरपाट-बेलन',            'NOS', 10,  50, true, now(), now()),
('BARTAN', 'तई',                     'NOS', 30,  50, true, now(), now()),
('BARTAN', 'स्ट्रे',                 'NOS', 20,  50, true, now(), now()),
('BARTAN', 'भोजन पत्ती (बड़ी थाली)', 'NOS', 20,  50, true, now(), now());
