-- UPI Donation bills — a separate table from `donation` on purpose, so these
-- counter-side UPI receipts never show up in existing donation reports/dashboard
-- aggregations (which only ever query the `donation` table).

CREATE SEQUENCE IF NOT EXISTS upi_donation_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE upi_donation (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_number     VARCHAR(50)  NOT NULL,
    donor_name         VARCHAR(255) NOT NULL,
    address            VARCHAR(500) NOT NULL,
    mobile             VARCHAR(10)  NOT NULL,
    purpose_id         BIGINT       NOT NULL,
    purpose_name_en    VARCHAR(255) NOT NULL,
    purpose_name_hi    VARCHAR(255) NOT NULL,
    amount             NUMERIC(12,2) NOT NULL,
    payment_ref_last4  VARCHAR(4)   NOT NULL,
    gotra_id           VARCHAR(50),
    gotra_name_en      VARCHAR(255),
    gotra_name_hi      VARCHAR(255),
    created_at         TIMESTAMP    NOT NULL,
    created_by         VARCHAR(100) NOT NULL,
    active             BOOLEAN      NOT NULL DEFAULT true,

    CONSTRAINT uk_upi_donation_receipt_number UNIQUE (receipt_number)
);
