-- Controls which top-level nav modules are visible to ADMIN and USER roles,
-- so modules can be rolled out phase-wise (Daan first, then Bichayat, then Bhakt Niwas).
-- SUPER_ADMIN always sees every module and is not represented here.

CREATE TABLE module_access_control (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_key         VARCHAR(50)  NOT NULL,
    display_name       VARCHAR(100) NOT NULL,
    enabled_for_admin  BOOLEAN      NOT NULL DEFAULT TRUE,
    enabled_for_user   BOOLEAN      NOT NULL DEFAULT FALSE,

    CONSTRAINT uk_module_access_control_module_key UNIQUE (module_key)
);

INSERT INTO module_access_control (module_key, display_name, enabled_for_admin, enabled_for_user) VALUES
    ('DAAN',        'Donation',    true, true),
    ('BICHAYAT',    'Bichayat',    true, false),
    ('BHAKT_NIWAS', 'Bhakt Niwas', true, false),
    ('REPORTS',     'Reports',     true, false),
    ('MASTER',      'Master',      true, false);
